name: Build Android APK

on:
  # يدوي - اضغط Run workflow من GitHub
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App Name'
        required: true
        default: 'EmergenX'
      version:
        description: 'Version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      build_type:
        description: 'Build Type'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - debug

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK (Release)
        if: ${{ github.event.inputs.build_type == 'release' }}
        run: |
          flutter build apk --release --split-per-abi
          echo "APK_PATH=build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk" >> $GITHUB_ENV

      - name: Build APK (Debug)
        if: ${{ github.event.inputs.build_type == 'debug' }}
        run: |
          flutter build apk --debug
          echo "APK_PATH=build/app/outputs/flutter-apk/app-debug.apk" >> $GITHUB_ENV

      - name: Rename APK
        run: |
          mkdir -p output
          cp ${{ env.APK_PATH }} output/${{ github.event.inputs.app_name }}-v${{ github.event.inputs.version }}.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.app_name }}-v${{ github.event.inputs.version }}-apk
          path: output/*.apk
          retention-days: 30

      - name: Build Summary
        run: |
          echo "## ✅ Build Successful!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| App Name | ${{ github.event.inputs.app_name }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Version | ${{ github.event.inputs.version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build Type | ${{ github.event.inputs.build_type }} |" >> $GITHUB_STEP_SUMMARY
          echo "| APK Size | $(du -h output/*.apk | cut -f1) |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Download the APK from the Artifacts section above." >> $GITHUB_STEP_SUMMARY
